# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9aa1545837c2a052a4a26d5820b8e5f4664f57474618c34f0d9aa94697ef05c2a10e6c222ccd2f76e12e5b985ca2ea7a02f37b73b604d67810dfb3e7e32d8ceb

test:
  secret_key_base: 8053b5f3fc821e54bf711d982a7a16d6bd5342316952d3d834e5d3ca2ab3d9d074fcdec5c7c077138df599a207366bc7cc7b32a9d7ed3336eb6696d545615817

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
